networks:
  ms:
    name: ms-network
    driver: bridge
    external: true

services:
  back_1:
    build:
      context: .
    container_name: book_01
    image: img_book_java
    ports:
      - "8100:8100"
    expose:
      - 8100
    environment:
      BOOK_USER_DB: ${BOOK_USER_DB}
      BOOK_PASSWORD_DB: ${BOOK_PASSWORD_DB}
      PORT: 8100
      HOST_EUREKA: eureka
      REDIS: redis
      REDIS_PORT: 6379
      SECRET: book-ms-pescador-relatividade
    networks:
      - ms

  back_2:
    build:
      context: .
    container_name: book_02
    image: img_book_java
    ports:
      - "8101:8100"
    expose:
      - 8101
    environment:
      BOOK_USER_DB: ${BOOK_USER_DB}
      BOOK_PASSWORD_DB: ${BOOK_PASSWORD_DB}
      PORT_DB: 5432
      PORT: 8101
      HOST_EUREKA: eureka
      REDIS: redis
      REDIS_PORT: 6379
      SECRET: book-ms-pescador-relatividade
    networks:
      - ms
