server:
  port: ${PORT}

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://${DATA_BASE}:5002/book_server
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://${DATA_BASE}:5002/book_server
    schemas: book
    user: postgres
    password: postgres

  sql:
    init:
      mode: always
      encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
