server:
  port: ${PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 3
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://${HOST_DB}/book?sslmode=require&channelBinding=require
    username: ${USER_DB}
    password: ${PASSWORD_DB}

  flyway:
    url: jdbc:postgresql://${HOST_DB}/book?sslmode=require&channelBinding=require
    schemas: book_server
    enabled: true
    user: ${USER_DB}
    password: ${PASSWORD_DB}

  sql:
    init:
      mode: always
      encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

security:
  jwt:
    public-key: classpath:${FOLDER_KEYS}/public.pem
    secret: ${SECRET}