server:
  port: 8100

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5002/book_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    name: book_server

  sql:
    init:
      mode: always
      encoding: utf-8

  flyway:
    url: jdbc:postgresql://localhost:5002/book_server
    schemas: book_server
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
