server:
  port: 8100

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5002/book_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      encoding: utf-8

  flyway:
    url: jdbc:postgresql://localhost:5002/
    schemas: book_server
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.dialect.PostgresPlusDialect
